name: Release

on:
  push:
    branches: [main, beta, test]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      HUSKY: '0'

    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint:fix
      - name: Test
        run: npm run test
      - name: Build
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'
        run: npm run build
      - name: Publish
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: npm run release
